### ISSUE TITLE
Mark the plugin compatible for EAP 2022.1

### ISSUE THREAD

**Issue by DAmNRelentless** [hsz/intellij-foldable-projectview#16]
The plugin is currently not compatible with the new EAP 2022.1 as it requires an earlier build. As far as I can see nothing has changed in the way plugins work so marking it as compatible should be enough.

**Comment by mojotx** [comment]
I wish there were easy step-by-step instructions on how to build the plugin locally, after bumping the supported version.

**Comment by DAmNRelentless** [comment]
You don't need to rebuild it. Just modify the file inside the jar.
Works fine except for the configuration window because it had changes in the version.

**Comment by BorzdeG** [comment]
Plugin works with release version 2022.1

**Comment by mallowigi** [comment]
[Foldable ProjectView-1.2.0.zip](https://github.com/hsz/intellij-foldable-projectview/files/9029093/Foldable.ProjectView-1.2.0.zip)

There. I built it for you.

(Good times, reminds me of the time I took the reins of the Material Theme project :) )
