### ISSUE TITLE
No way to hide ignored files

### ISSUE THREAD

**Issue by Recks11** [hsz/intellij-foldable-projectview#2]
### The plugin provides no option to hide ignored files.

There is no way or rule that can handle all files in a `.gitignore` file.

**Comment by hsz** [comment]
Thanks for reporting, @Recks11!

Soon, I will introduce a named folder (#3) that will let you define multiple sets of rules.
In addition to that, it'd be possible to pick an existing ignore-like file instead of providing the list manually (#4).

**Comment by Recks11** [comment]
can I make a PR to show you a fix I made?

**Comment by hsz** [comment]
Sure! I'm always happy with PRs. :)

**Comment by hsz** [comment]
Good job, thanks! I'm going to release it now.

**Comment by hsz** [comment]
I had to introduce an extra listener for refresh ProjectView when VCS changelists have changed: 1af18db
