### ISSUE TITLE
Feature Request: config file in root

### ISSUE THREAD

**Issue by gjrtimmer** [hsz/intellij-foldable-projectview#29]
# Feature Request

Please implement the possibility to add files to a certain config file in the root of a project which defines which files/folders to hide.
This will allow easy portable configuration between repositories.

**Comment by kawazoe** [comment]
This could be easily fixed by saving the configs into its own configuration file instead of the `workspace.xml` file, like what the Git Toolbox plugin is doing for project specific settings.

**Comment by hsz** [comment]
Implemented with b239b6b9ae192a76aa9c3e34a4693a490f7bfee9
Will be released with v2.0.0
