### ISSUE TITLE
Plugin settings are not visible

### ISSUE THREAD

**Issue by Coobaha** [hsz/intellij-foldable-projectview#8]
Hi @hsz , for some reason preferences pane is not visible in pref modal. I can see it in actions, but it leads to wrong location

![image](https://user-images.githubusercontent.com/2446638/127968792-f2d59dd6-7a70-4934-8497-1f5bf69ca298.png)

After clicking it opens Package Search 😒 

![image](https://user-images.githubusercontent.com/2446638/127968822-0b4c376b-3ae8-48af-a341-59995842c2b1.png)

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5

plugin version ski.chrzanow.foldableprojectview (1.1.0)
```

**Comment by hsz** [comment]
Thanks for reporting, it's fixed and will be available within minutes in the v1.1.1 release.
